update mathjax cdn
cosname/hugo-steam-cos pull request #3
Opened 2017-04-05 13:18 UTC by fyears

https://www.mathjax.org/cdn-shutting-down/

mathjax 没钱了，推荐大家用 cloudflare 的 cdn 😟

2017-04-05 16:51 UTC, yihui requested changes

2017-04-05 16:51 UTC, yihui commented on layouts/partials/footer.html
> +<script async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
不能用 async，下面马上还需要用到 MathJax.Hub。

2017-04-05 16:52 UTC, yihui commented
居然关门了……

2017-04-05 17:01 UTC, yixuan commented
真是猝不及防……

2017-04-05 17:04 UTC, yixuan commented
他们家是4月1号发的消息。 😅

2017-04-05 17:05 UTC, fyears commented
不是关门，是没钱付账 cdn 了。

我看了那篇文章，挺好笑的，cloudflare 说它们几十 tb 流量要升价，开发者不干了，直接关掉自己付账的业务，呼吁大家直接用 cloudflare 的公共福利 cdn。一套句真是猝不及防啊……

2017-04-05 17:15 UTC, yihui approved these changes

2017-04-05 20:23 UTC, merged

2017-04-06 14:37 UTC, fyears commented
顺便说一下，cdnjs 的速度在国内**极其**慢。这个设置只是权宜之计，日后，如果主要面对国内读者，恐怕要换成 http://www.bootcdn.cn/mathjax/ 或 https://staticfile.org/ 。

2017-04-06 16:13 UTC, yihui commented
那就换吧。

2017-04-07 06:06 UTC, yihui commented
我已经换到 BootCDN